#!/bin/bash
LAST_CHAPTER=$(tail -1 goblin_slayer.txt)
echo "last chapter: "$LAST_CHAPTER
NEW_CHAPTER=$((LAST_CHAPTER+1))

NEW_CHAPTER_URL="http://manga.watchgoblinslayer.com/chapter/goblin-slayer-chapter-$NEW_CHAPTER/"
CURL_RETURN=$(curl -o /dev/null -s -w "%{http_code}\n" "$NEW_CHAPTER_URL")

if [ $CURL_RETURN -eq 200 ]; then
    echo $NEW_CHAPTER_URL
else
    echo "Pas de nouveau chapitre"
fi
