#!/bin/bash
LAST_CHAPTER=$(tail -1 kingdom.txt)
echo "last chapter: "$LAST_CHAPTER
NEW_CHAPTER=$((LAST_CHAPTER+1))

if [ $NEW_CHAPTER -lt 100 ]; then
    NEW_CHAPTER="0$NEW_CHAPTER"
fi

NEW_CHAPTER_URL="https://ww2.readkingdom.com/chapter/kingdom-chapter-$NEW_CHAPTER/"
CURL_RETURN=$(curl -o /dev/null -s -w "%{http_code}\n" "$NEW_CHAPTER_URL")

if [ $CURL_RETURN -eq 200 ]; then
    echo $NEW_CHAPTER_URL
else
    echo "Pas de nouveau chapitre"
fi
